export const Province = {
	"آذربایجان شرقى": "Eastern Azarbayjan",
	"آذرباىجان غربى": "Western Azarbayjan",
	"اردبیل": "Ardebil",
	"اصفهان": "Isfahan",
	"البرز": "Alborz",
	"ایلام": "Ilam",
	"بوشهر": "Bousher",
	"تهران": "Tehran",
	"چهارمحال و بختیارى": "Chahar Mahal o Bakhtiari",
	"خراسان جنوبى": "Khorasan Jonoubi",
	"خراسان رضوى": "Khorasan Razavi",
	"خراسان شمالى": "Khorasan Shomali",
	"خوزستان": "Khouzestan",
	"زنجان": "Zanjan",
	"سمنان": "Semnan",
	"سیستان و بلوچستان": "Sistan O Balouchestan",
	"فارس": "Fars",
	"قزوین": "Qazvin",
	"قم": "Qom",
	"کردستان": "Kordestan",
	"کرمان": "Kerman",
	"کرمانشاه": "Kermanshah",
	"کهکیلویه و بویراحمد": "Kohkiloyeh va Bouyerahmad",
	"گلستان": "Golestan",
	"گیلان": "Gilan",
	"لرستان": "Lorestan",
	"مازندران": "Mazandaran",
	"مرکزى": "Markazi",
	"هرمزگان": "Hormozgan_ rovince",
	"همدان": "Hamedan",
	"یزد": "Yazd"
}

export const Cities = {
	"اهر": "Ahar",
	"عجبشیر": "Ajabshir",
	"آذر شهر": "Azarshahr",
	"بناب": "bonab",
	"بستان آباد": "Bostanabad",
	"چاراویماق": "Charuymaq",
	"هشترود": "Hashtrud",
	"هریس": "Heris",
	"جلفا": "Jolfa",
	"کلیبر": "Kaleybar",
	"خداآفرین": "Khoda Afarin",
	"ملکان": "Malekan",
	"مراغه": "Maragheh",
	"میانه": "Meyaneh",
	"مرند": "Marand",
	"اسکو": "Osku",
	"سراب": "Sarab",
	"شبستر": "Shabestar",
	"تبریز": "Tabriz",
	"ورزقان": "Varzaqan",
	"ارومیه": "Urmia",
	"نقده": "Naqadeh",
	"ماکو": "Maku",
	"تکاب": "Takab",
	"خوى": "Khoy",
	"مهاباد": "Mahabad",
	"سر دشت": "Sardasht",
	"چالدران": "Chaldoran",
	"بوکان": "Bukan",
	"میاندوآب": "Miandoab",
	"سلماس": "Salmas",
	"شاهین دژ": "Shahin Dezh",
	"پیرانشهر": "Piranshahr",
	"اشنویه": "Oshnavieh",
	"چایپاره": "Chaypareh",
	"پلدشت": "Poldasht",
	"شوط": "Showt",
	"اردبیل": "Ardabil",
	"سرعین": "Sareyn",
	"بیله سوار": "Bileh Savar",
	"پارس آباد": "Parsabad",
	"خلخال": "Khalkhal",
	"مشگین شهر": "Meshgin Shahr",
	"نمین": "Namin",
	"نیر": "Nir",
	"کوثر": "Kowsar",
	"گرمى": "Germi",
	"بوئین و میاندشت": "Buin va Miandasht",
	"مبارکه": "Mobarakeh",
	"اردستان": "Ardestan",
	"خور و بیابانک": "Khur and Biabanak",
	"فلاورجان": "Falavarjan",
	"فریدون شهر": "Fereydunshahr",
	"کاشان": "Kashan",
	"لنجان": "Lenjan",
	"گلپایگان": "Golpayegan",
	"فریدن": "Faridan",
	"نایین": "Nain",
	"اصفهان": "Isfahan",
	"نجف آباد": "Najafabad",
	"آران و بیدگل": "Aran o Bidgol",
	"چادگان": "Chadegan",
	"تیران و کرون": "Tiran and Karvan",
	"شهرضا": "Shahreza",
	"سمیرم": "Semirom",
	"خمینى شهر": "Khomeyni Shahr",
	"دهاقان": "Dehaqan",
	"نطنز": "Natanz",
	"برخوار": "borkhar",
	"شاهین شهر و میمه": "Shahin Shahr and Meymeh",
	"خوانسار": "Khvansar",
	"ایلام": "Ilam",
	"مهران": "Mehran",
	"دهلران": "Dehloran",
	"آبدانان": "Abdanan",
	"چرداول": "Chardaval",
	"دره شهر": "Darreh Shahr",
	"ایوان": "Eyvan",
	"بدره": "Badreh",
	"سیروان": "Sirvan",
	"ملکشاهى": "Malekshahi",
	"عسلویه": "Asaluyeh",
	"گناوه": "Ganaveh",
	"دشتى": "Dashti",
	"دشتستان": "Dashtestan",
	"دیر": "Deyr",
	"بوشهر": "Bushehr",
	"کنگان": "Kangan",
	"تنگستان": "Tangestan",
	"دیلم": "Deylam",
	"جم": "Jam",
	"قرچک": "Qarchak",
	"پردیس": "Pardis",
	"بهارستان": "Baharestan",
	"شمیرانات": "Shemiran",
	"رباط کریم": "Robat Karim",
	"فیروزکوه": "FiruzkKuh",
	"تهران": "Tehran",
	"ورامین": "Varamin",
	"اسلامشهر": "Eslamshahr",
	"رى": "Ray",
	"پاکدشت": "Pakdasht",
	"پیشوا": "Pishva",
	"قدس": "Qods",
	"ملارد": "Malard",
	"شهریار": "Shahriar",
	"دماوند": "Damavand",
	"بن": "Bon",
	"سامان": "Saman",
	"کیار": "Kiar",
	"بروجن": "Borujen",
	"اردل": "Ardal",
	"شهرکرد": "Shahrekord",
	"فارسان": "Farsan",
	"کوهرنگ": "Kuhrang",
	"لردگان": "Lordegan",
	"داورزن": "Davarzan",
	"کلات": "Kalat",
	"بردسکن": "Bardaskan",
	"مشهد": "Mashhad",
	"نیشابور": "Nishapur",
	"سبزوار": "Sabzevar",
	"کاشمر": "Kashmar",
	"گناباد": "Gonabad",
	"تربت حیدریه": "Torbat Heydarieh",
	"خواف": "Khvaf",
	"تربت جام": "Torbat Jam",
	"تایباد": "Taybad",
	"مه ولات": "Mahvelat",
	"چناران": "Chenaran",
	"درگز": "Dargaz",
	"فیروزه": "Firuzeh",
	"قوچان": "Quchan",
	"سرخس": "Sarakhs",
	"رشتخوار": "Rashtkhvar",
	"بینالود": "Binaloud",
	"زاوه": "Zaveh",
	"جوین": "Jowayin",
	"بجستان": "Bajestan",
	"باخزر": "Bakharz",
	"فریمان": "Fariman",
	"خلیل آباد": "Khalilabad",
	"جغتاى": "Joghatai",
	"خوشاب": "Khoshab",
	"زیرکوه": "Zirkuh",
	"خوسف": "Khusf",
	"درمیان": "Darmian",
	"قائنات": "Qaen",
	"بشرویه": "Boshruyeh",
	"فردوس": "Ferdows",
	"بیرجند": "Birjand",
	"نهبندان": "Nehbandan",
	"سربیشه": "Sarbisheh",
	"سرایان": "Sarayan",
	"طبس": "Tabas",
	"بجنورد": "Bojnord",
	"راز و جرگلان": "Raz and Jargalan",
	"اسفراین": "Esfarayen",
	"جاجرم": "Jajrom",
	"شیروان": "Shirvan",
	"مانه و سملقان": "Maneh and Samalqan",
	"گرمه": "Garmeh",
	"فاروج": "Faruj",
	"کارون": "Karun",
	"حمیدیه": "Hamidiyeh",
	"آغاجرى": "Aghajari",
	"شوشتر": "Shushtar",
	"دشت آزادگان": "Dasht-e Azadegan",
	"امیدیه": "Omidiyeh",
	"گتوند": "Gotvand",
	"شادگان": "Shadegan",
	"دزفول": "Dezful",
	"رامشیر": "Ramshir",
	"بهبهان": "Behbahan",
	"باوى": "Bavi",
	"اندیمشک": "Andimeshk",
	"اهواز": "Ahvaz",
	"اندیکا": "Andika",
	"شوش": "Shush",
	"آبادان": "Abadan",
	"هندیجان": "Hendijan",
	"خرمشهر": "Khorramshahr",
	"مسجد سلیمان": "Masjed Soleyman",
	"ایذه": "Izeh",
	"رامهرمز": "Ramhormoz",
	"باغ ملک": "Bagh Malek",
	"هفتکل": "Haftkel",
	"هویزه": "Hoveyzeh",
	"ماهشهر": "Mahshahr",
	"لالى": "Lali",
	"زنجان": "Zanjan",
	"ابهر": "Abhar",
	"خدابنده": "Khodabandeh",
	"ماهنشان": "Mahneshan",
	"خرمدره": "Khorramdarreh",
	"ایجرود": "Ijrud",
	"طارم": "Tarom",
	"سلطانیه": "Soltaniyeh",
	"سمنان": "Semnan",
	"شاهرود": "Shahrud",
	"گرمسار": "Garmsar",
	"سرخه": "Sorkheh",
	"دامغان": "Damghan",
	"آرادان": "Aradan",
	"مهدى شهر": "Mehdishahr",
	"میامى": "Meyami",
	"زاهدان": "Zahedan",
	"بمپور": "Bampur",
	"چابهار": "Chabahar",
	"خاش": "Khash",
	"سراوان": "Saravan",
	"زابل": "Zabol",
	"سرباز": "Sarbaz",
	"قصر قند": "Qasr-e Qand",
	"نیکشهر": "Nik Shahr",
	"کنارک": "Konarak",
	"ایرانشهر": "Iranshahr",
	"زهک": "Zehak",
	"سیب و سوران": "Sib and Suran",
	"میرجاوه": "Mirjaveh",
	"دلگان": "Dalgan",
	"هیرمند": "Hirmand",
	"مهرستان": "Mehrestan",
	"فنوج": "Fanuj",
	"هامون": "Hamoun",
	"نیمروز": "Nimrouz",
	"شیراز": "Shiraz",
	"اقلید": "Eqlid",
	"داراب": "Darab",
	"فسا": "Fasa",
	"مرودشت": "Marvdasht",
	"خرم بید": "Khorrambid",
	"آباده": "Abadeh",
	"کازرون": "Kazerun",
	"گراش": "Gerash",
	"ممسنى": "Mamasani",
	"سپیدان": "Sepidan",
	"لارستان": "Larestan",
	"فیروز آباد": "Firuzabad",
	"جهرم": "Jahrom",
	"نی ریز": "Neyriz",
	"استهبان": "Estahban",
	"لامرد": "Lamerd",
	"مهر": "Mohr",
	"پاسارگاد": "Pasargad",
	"ارسنجان": "Arsanjan",
	"قیروکارزین": "Qir and Karzin",
	"رستم": "Rostam",
	"فراشبند": "Farashband",
	"سروستان": "Sarvestan",
	"زرین دشت": "Zarrin Dasht",
	"کوار": "Kavar",
	"بوانات": "Bavanat",
	"خرامه": "Kharameh",
	"خنج": "Khonj",
	"قزوین": "Qazvin",
	"تاکستان": "Takestan",
	"آبیک": "Abyek",
	"بوئین زهرا": "Buin Zahra",
	"البرز": "Alborz",
	"آوج": "Avaj",
	"قم": "Qom",
	"طالقان": "Taleqan",
	"اشتهارد": "Eshtehard",
	"کرج": "Karaj",
	"نظر آباد": "Nazarabad",
	"ساوجبلاغ‎": "Savojbolagh",
	"فردیس": "Fardis",
	"سنندج": "Sanandaj",
	"دیواندره": "Divandarreh",
	"بانه": "Baneh",
	"بیجار": "Bijar",
	"سقز": "Saqqez",
	"کامیاران": "Kamyaran",
	"قروه": "Qorveh",
	"مریوان": "Marivan",
	"سروآباد‎": "Sarvabad",
	"دهگلان‎": "Dehgolan",
	"کرمان": "Kerman",
	"راور": "Ravar",
	"شهر بابک": "Shahr-e Babak",
	"انار": "Anar",
	"کوهبنان": "Kuhbanan",
	"رفسنجان": "Rafsanjan",
	"سیرجان": "Sirjan",
	"کهنوج": "Kahnuj",
	"زرند": "Zarand",
	"ریگان": "Rigan",
	"بم": "Bam",
	"جیرفت": "Jiroft",
	"عنبرآباد": "Anbarabad",
	"بافت": "Baft",
	"ارزوئیه": "Arzuiyeh",
	"بردسیر": "Bardsir",
	"فهرج": "Fahraj",
	"فاریاب": "Faryab",
	"منوجان": "Manujan",
	"نرماشیر": "Narmashir",
	"قلعه گنج": "Qaleh Ganj",
	"رابر": "Rabor",
	"رودبار جنوب": "Rudbar-e Jonubi",
	"کرمانشاه": "Kermanshah",
	"اسلام آباد غرب": "Eslamabad-e Gharb",
	"سر پل ذهاب": "Sarpol-e Zahab",
	"کنگاور": "Kangavar",
	"سنقر": "Sonqor",
	"قصر شیرین": "Qasr-e Shirin",
	"گیلان غرب": "Gilan-e Gharb",
	"هرسین": "Harsin",
	"صحنه": "Sahneh",
	"پاوه": "Paveh",
	"جوانرود": "Javanrud",
	"دالاهو": "Dalahu",
	"روانسر": "Ravansar",
	"ثلاث باباجانى": "Salas-e Babajani",
	"یاسوج": "Yasuj",
	"گچساران": "Gachsaran",
	"دنا": "Dana",
	"کهگیلویه‎": "Kohgiluyeh",
	"لنده": "Landeh",
	"بهمئى": "Bahmai",
	"باشت": "Basht",
	"بویراحمد": "Boyer Ahmad",
	"چرام": "Charam",
	"گرگان": "Gorgan",
	"آق قلا": "Aqqala",
	"گنبد کاووس": "Gonbad-e Qabus",
	"على آباد": "Aliabad",
	"مینو دشت": "Minudasht",
	"ترکمن": "Torkaman",
	"کردکوى": "Kordkuy",
	"بندر گز": "Bandar-e Gaz",
	"کلاله": "Kalaleh",
	"آزاد شهر": "Azadshahr",
	"رامیان": "Ramian",
	"گالیکش‎": "Galikash",
	"مراوه تپه": "Maraveh Tappeh",
	"گمیشان": "Gomishan",
	"رشت": "Rasht",
	"لنگرود": "Langarud",
	"رودسر": "Rudsar",
	"طوالش": "Talesh",
	"آستارا": "Astara",
	"آستانه اشرفیه": "Astaneh-ye Ashrafiyeh",
	"رودبار": "Rudbar",
	"فومن": "Fuman",
	"صومعه سرا": "Sowme-eh Sara",
	"بندرانزلى": "Bandar-e Anzali",
	"رضوانشهر": "Rezvanshahr",
	"ماسال": "Masal",
	"شفت": "Shaft",
	"سیاهکل": "Siahkal",
	"املش": "Amlash",
	"لاهیجان": "Lahijan",
	"خرم آباد": "Khorramabad",
	"دلفان": "Delfan",
	"بروجرد": "Borujerd",
	"دورود": "Dorud",
	"الیگودرز": "Aligudarz",
	"ازنا": "Azna",
	"کوهدشت": "Kuhdasht",
	"سلسله": "Selseleh",
	"پلدختر": "Pol-e Dokhtar",
	"دوره": "Dowreh",
	"رومشکان": "Rumeshkhan",
	"سارى": "Sari",
	"آمل": "Amol",
	"بابل": "Babol",
	"بابلسر": "Babolsar",
	"بهشهر": "Behshahr",
	"تنکابن": "Tonekabon",
	"جویبار": "Juybar",
	"چالوس": "Chalus",
	"رامسر": "Ramsar",
	"سواد کوه": "Savadkuh",
	"قائم شهر": "Qaem Shahr",
	"نکا": "Neka",
	"نور": "Nur",
	"نوشهر": "Nowshahr",
	"محمودآباد": "Mahmudabad",
	"فریدونکنار": "Fereydunkenar",
	"عباس آباد": "Abbasabad",
	"گلوگاه": "Galugah",
	"میاندورود": "Miandorud",
	"سیمرغ": "Simorgh",
	"کلاردشت": "Kelardasht",
	"سوادکوه شمالى": "Savadkooh Shomali",
	"اراک": "Arak",
	"آشتیان": "Ashtian",
	"تفرش": "Tafresh",
	"خمین": "Khomeyn",
	"دلیجان": "Delijan",
	"ساوه": "Saveh",
	"زرندیه": "Zarandieh",
	"محلات": "Mahallat",
	"شازند": "Shazand",
	"فراهان": "Farahan",
	"خنداب": "Khondab",
	"کمیجان": "Komijan",
	"بندرعباس": "Bandar Abbas",
	"قشم": "Qeshm",
	"بندر لنگه": "Bandar Lengeh",
	"بستک": "Bastak",
	"حاجى آباد هرمزگان": "Hajjiabad Hormozgan",
	"رودان": "Rudan",
	"میناب": "Minab",
	"ابوموسى": "Abumusa",
	"جاسک": "Jask",
	"خمیر": "Khamir",
	"پارسیان": "Parsian",
	"بشاگرد": "Bashagard",
	"سیریک": "Sirik",
	"حاجی آباد": "Hajjiabad",
	"همدان": "Hamadan",
	"ملایر": "Malayer",
	"تویسرکان": "Tuyserkan",
	"نهاوند": "Nahavand",
	"کبودر اهنگ": "Kabudarahang",
	"رزن": "Razan",
	"اسدآباد": "Asadabad",
	"بهار": "Bahar",
	"فامنین": "Famenin",
	"یزد": "Yazd",
	"تفت": "Taft",
	"اردکان": "Ardakan",
	"ابرکوه": "Abarkuh",
	"میبد": "Meybod",
	"بافق": "Bafq",
	"صدوق": "Saduq",
	"مهریز": "Mehriz",
	"خاتم": "Khatam"
}

export const getCurrentCity = (en) => {
  for (let key in Cities) {
    if (key.toLowerCase() === en) {
      return Cities[key];
    }
  }
  return null;
};